---
abstract: 'A class based representation of an InterMine DB schema'
author:
  - 'Alex Kalderimis <dev@intermine.org>'
build_requires:
  Test::Exception: 0
  Test::More: 0.95
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3624'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: InterMine-Model
provides:
  InterMine::Model:
    file: lib/InterMine/Model.pm
    version: 0.9701
  InterMine::Model::Attribute:
    file: lib/InterMine/Model/Attribute.pm
  InterMine::Model::ClassDescriptor:
    file: lib/InterMine/Model/ClassDescriptor.pm
  InterMine::Model::Collection:
    file: lib/InterMine/Model/Collection.pm
  InterMine::Model::Handler:
    file: lib/InterMine/Model/Handler.pm
  InterMine::Model::Object:
    file: lib/InterMine/Model/Object.pm
  InterMine::Model::Reference:
    file: lib/InterMine/Model/Reference.pm
  InterMine::Model::Role::Descriptor:
    file: lib/InterMine/Model/Role/Descriptor.pm
  InterMine::Model::Role::Field:
    file: lib/InterMine/Model/Role/Field.pm
  InterMine::Model::TestModel:
    file: lib/InterMine/Model/TestModel.pm
  InterMine::Model::Types:
    file: lib/InterMine/Model/Types.pm
requires:
  Carp: 0
  Moose: 2
  Moose::Util::TypeConstraints: 2
  MooseX::Role::WithOverloading: 0
  MooseX::Types: 0
  Scalar::Util: 0
  Time::HiRes: 0
  XML::Parser::PerlSAX: 0.08
  perl: v5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.9701
